<!doctype html >
<!--[if IE 8]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html lang="en-US" itemscope itemtype="http://schema.org/Blog" prefix="og: http://ogp.me/ns#">
<!--<![endif]-->

<!-- Mirrored from topdev.vn/blog/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 28 Feb 2018 15:00:40 GMT -->
<!-- Added by HTTrack -->
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<!-- /Added by HTTrack -->

<head>
    <title>TopDev | Happy coding!</title>
    
    <link rel='stylesheet' id='google_font_open_sans-css' href='https://fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C600italic%2C400%2C600%2C700&amp;subset=vietnamese&amp;ver=4.8.1' type='text/css' media="print" onload="media='all'" />
    <link rel='stylesheet' id='google_font_roboto-css' href='https://fonts.googleapis.com/css?family=Roboto%3A500%2C400italic%2C700%2C900%2C500italic%2C400%2C300&amp;subset=vietnamese&amp;ver=4.8.1' type='text/css' media="print" onload="media='all'" />
    <link rel='stylesheet' id='js_composer_front-css' href="{{asset('theme/client/plugins/js_composer/assets/css/js_composer.min972f.css?ver=5.0.1')}}" type='text/css' media="print" onload="media='all'" />
    <link rel='stylesheet' id='td-theme-css' href="{{asset('theme/client/themes/Newspaper/stylee87d.css?ver=7.6')}}" type='text/css' media='all' />
    <script type='text/javascript' src="{{asset('theme/client/js/jquery/jqueryb8ff.js?ver=1.12.4')}}"></script>
    <script type='text/javascript' src="{{asset('theme/client/js/jquery/jquery-migrate.min330a.js?ver=1.4.1')}}">
      
    </script>
    <script type='text/javascript'>
        /* <![CDATA[ */
        var CrayonSyntaxSettings = {
            "version": "_2.7.2_beta",
            "is_admin": "0",
            "ajaxurl": "https:\/\/topdev.vn\/blog\/wp-admin\/admin-ajax.php",
            "prefix": "crayon-",
            "setting": "crayon-setting",
            "selected": "crayon-setting-selected",
            "changed": "crayon-setting-changed",
            "special": "crayon-setting-special",
            "orig_value": "data-orig-value",
            "debug": ""
        };
        var CrayonSyntaxStrings = {
            "copy": "Press %s to Copy, %s to Paste",
            "minimize": "Click To Expand Code"
        };
        /* ]]> */
    </script>
    <script type='text/javascript' src="{{asset('theme/client/plugins/crayon-syntax-highlighter/js/min/crayon.min2f6a.js?ver=_2.7.2_beta')}}"></script>
    <script type='text/javascript' src="{{asset('theme/client/plugins/revslider/public/assets/js/jquery.themepunch.tools.mina88c.js?ver=5.3.0.2')}}"></script>
    <script type='text/javascript' src="{{asset('theme/client/plugins/revslider/public/assets/js/jquery.themepunch.revolution.mina88c.js?ver=5.3.0.2')}}"></script>
    <link rel='https://api.w.org/' href='wp-json/index.html' />
    <link rel="EditURI" type="application/rsd+xml" title="RSD" href="xmlrpc0db0.html?rsd" />
    <link rel="wlwmanifest" type="application/wlwmanifest+xml" href="wp-includes/wlwmanifest.xml" />
    <meta name="generator" content="WordPress 4.8.1" />
    <link rel='shortlink' href='index.html' />
    <link rel="alternate" type="application/json+oembed" href="wp-json/oembed/1.0/embedc432.json?url=https%3A%2F%2Ftopdev.vn%2Fblog%2F" />
    <link rel="alternate" type="text/xml+oembed" href="wp-json/oembed/1.0/embed8c1b?url=https%3A%2F%2Ftopdev.vn%2Fblog%2F&amp;format=xml" />
    <!--[if lt IE 9]><script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->


    <meta name="generator" content="Powered by Slider Revolution 5.3.0.2 - responsive, Mobile-Friendly Slider Plugin for WordPress with comfortable drag and drop interface." />

    <!-- JS generated by theme -->

    <script>
        

        
        var td_ajax_url = "index.html\/\/topdev.vn\/blog\/wp-admin\/admin-ajax.php?td_theme_name=Newspaper&v=7.6";
        var td_get_template_directory_uri = "index.html\/\/topdev.vn\/blog\/wp-content\/themes\/Newspaper";
        var tds_snap_menu = "";
        var tds_logo_on_sticky = "";
        var tds_header_style = "7";
        var td_please_wait = "Please wait...";
        var td_email_user_pass_incorrect = "User or password incorrect!";
        var td_email_user_incorrect = "Email or username incorrect!";
        var td_email_incorrect = "Email incorrect!";
        var tds_more_articles_on_post_enable = "";
        var tds_more_articles_on_post_time_to_wait = "";
        var tds_more_articles_on_post_pages_distance_from_top = 3000;
        var tds_theme_color_site_wide = "#d7422f";
        var tds_smart_sidebar = "";
        var tdThemeName = "Newspaper";
        var td_magnific_popup_translation_tPrev = "Previous (Left arrow key)";
        var td_magnific_popup_translation_tNext = "Next (Right arrow key)";
        var td_magnific_popup_translation_tCounter = "%curr% of %total%";
        var td_magnific_popup_translation_ajax_tError = "The content from %url% could not be loaded.";
        var td_magnific_popup_translation_image_tError = "The image #%curr% could not be loaded.";
        var td_ad_background_click_link = "";
        var td_ad_background_click_target = "";
    </script>

    <script>
        (function(i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function() {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '../../www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-64352659-1', 'auto');
        ga('send', 'pageview');
    </script>
    <noscript>
        <style type="text/css">
            .wpb_animate_when_almost_visible {
                opacity: 1;
            }
        </style>
    </noscript>
</head>

<body class="home page-template-default page page-id-3702 home-2 wpb-js-composer js-comp-ver-5.0.1 vc_responsive td-full-layout" itemscope="itemscope" itemtype="https://schema.org/WebPage">

    <div class="td-scroll-up"><i class="td-icon-menu-up"></i></div>

    <div class="td-menu-background"></div>
    <div id="td-mobile-nav">
        <div class="td-mobile-container">
            <!-- mobile menu top section -->
            <div class="td-menu-socials-wrap">
                <!-- socials -->
                <div class="td-menu-socials">

                    <span class="td-social-icon-wrap">
            <a target="_blank" href="https://www.facebook.com/topdevvietnam/" title="Facebook">
                <i class="td-icon-font td-icon-facebook"></i>
            </a>
        </span> </div>
                <!-- close button -->
                <div class="td-mobile-close">
                    <a href="#"><i class="td-icon-close-mobile"></i></a>
                </div>
            </div>

            <!-- login section -->

            <!-- menu section -->
            <div class="td-mobile-content">
                <div class="menu-main-menu-container">
                    <ul id="menu-main-menu" class="td-mobile-main-menu">
                        <li id="menu-item-1085" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-first menu-item-1085"><a href="category/jobs/index.html">Hot Jobs</a></li>
                        <li id="menu-item-4" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-4"><a href="category/ask-me-anything/index.html">AMA</a></li>
                        <li id="menu-item-5" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-5"><a href="category/event/index.html">Event</a></li>
                        <li id="menu-item-7" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-7"><a href="category/hr/index.html">HR</a></li>
                        <li id="menu-item-8" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-8"><a href="category/lap-trinh/index.html">Lập Trình</a></li>
                        <li id="menu-item-9" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-9"><a href="category/phong-van/index.html">Phỏng vấn</a></li>
                        <li id="menu-item-1083" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-1083"><a href="category/cong-nghe/index.html">Công nghệ</a></li>
                        <li id="menu-item-1084" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-1084"><a href="category/design/index.html">Design</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- register/login section -->
    </div>
    <div class="td-search-background"></div>
    <div class="td-search-wrap-mob">
        <div class="td-drop-down-search" aria-labelledby="td-header-search-button">
            <form method="get" class="td-search-form" action="https://topdev.vn/blog/">
                <!-- close button -->
                <div class="td-search-close">
                    <a href="#"><i class="td-icon-close-mobile"></i></a>
                </div>
                <div role="search" class="td-search-input">
                    <span>Search</span>
                    <input id="td-header-search-mob" type="text" value="" name="s" autocomplete="off" />
                </div>
            </form>
            <div id="td-aj-search-mob"></div>
        </div>
    </div>
    <div id="td-outer-wrap">

        <!--
Header style 7
-->

        <div class="td-header-wrap td-header-style-7">
            <div class="td-header-top-menu-full">
                <div class="td-container td-header-row td-header-top-menu">

                    <div class="top-bar-style-1">

                        <div class="td-header-sp-top-menu">

                            <div class="menu-top-container">
                                <ul id="menu-top-menu" class="top-header-menu">
                                    <li id="menu-item-10" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-first td-menu-item td-normal-menu menu-item-10"><a href="https://topdev.vn/">TopDev Jobs</a></li>
                                    <li id="menu-item-11" class="menu-item menu-item-type-custom menu-item-object-custom td-menu-item td-normal-menu menu-item-11"><a href="https://techtalk.vn/">TechTalk</a></li>
                                    <li id="menu-item-12" class="menu-item menu-item-type-custom menu-item-object-custom td-menu-item td-normal-menu menu-item-12"><a href="http://devvui.com/">Devvui</a></li>
                                    <li id="menu-item-13" class="menu-item menu-item-type-custom menu-item-object-custom td-menu-item td-normal-menu menu-item-13"><a href="http://mobileday.vn/">MobileDay</a></li>
                                    <li id="menu-item-14" class="menu-item menu-item-type-custom menu-item-object-custom td-menu-item td-normal-menu menu-item-14"><a href="https://vietnamwebsummit.com/">VietNam Web Summit</a></li>
                                    <li id="menu-item-15" class="menu-item menu-item-type-custom menu-item-object-custom td-menu-item td-normal-menu menu-item-15"><a href="http://onsite.applancer.net/">TopDev Onsite</a></li>
                                    <li id="menu-item-16" class="menu-item menu-item-type-custom menu-item-object-custom td-menu-item td-normal-menu menu-item-16"><a href="https://salary.topdev.vn/">Salary</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <!-- LOGIN MODAL -->

                    <div id="login-form" class="white-popup-block mfp-hide mfp-with-anim">
                        <div class="td-login-wrap">
                            <a href="#" class="td-back-button"><i class="td-icon-modal-back"></i></a>
                            <div id="td-login-div" class="td-login-form-div td-display-block">
                                <div class="td-login-panel-title">Sign in</div>
                                <div class="td-login-panel-descr">Welcome! Log into your account</div>
                                <div class="td_display_err"></div>
                                <div class="td-login-inputs">
                                    <input class="td-login-input" type="text" name="login_email" id="login_email" value="" required>
                                    <label>your username</label>
                                </div>
                                <div class="td-login-inputs">
                                    <input class="td-login-input" type="password" name="login_pass" id="login_pass" value="" required>
                                    <label>your password</label>
                                </div>
                                <input type="button" name="login_button" id="login_button" class="wpb_button btn td-login-button" value="Login">
                                <div class="td-login-info-text"><a href="#" id="forgot-pass-link">Forgot your password? Get help</a></div>

                            </div>

                            <div id="td-forgot-pass-div" class="td-login-form-div td-display-none">
                                <div class="td-login-panel-title">Password recovery</div>
                                <div class="td-login-panel-descr">Recover your password</div>
                                <div class="td_display_err"></div>
                                <div class="td-login-inputs">
                                    <input class="td-login-input" type="text" name="forgot_email" id="forgot_email" value="" required>
                                    <label>your email</label>
                                </div>
                                <input type="button" name="forgot_button" id="forgot_button" class="wpb_button btn td-login-button" value="Send My Password">
                                <div class="td-login-info-text">A password will be e-mailed to you.</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="td-header-menu-wrap-full">
                <div class="td-header-menu-wrap td-header-gradient">
                    <div class="td-container td-header-row td-header-main-menu">
                        <div class="td-header-sp-logo">
                            <h1 class="td-logo">        <a class="td-main-logo" href="index.html">
            <img class="td-retina-data" data-retina="https://blog.topdev.vn/{{asset('theme/client/uploads/2017/01/logotopdev.png')}}" src="{{asset('theme/client/uploads/2017/01/logotopdev.png')}}" alt=""/>
            <span class="td-visual-hidden">TopDev</span>
        </a>
    </h1> </div>
                        <div id="td-header-menu" role="navigation">
                            <div id="td-top-mobile-toggle"><a href="#"><i class="td-icon-font td-icon-mobile"></i></a></div>
                            <div class="td-main-menu-logo td-logo-in-header">
                                <a class="td-mobile-logo td-sticky-disable" href="index.html">
                                    <img class="td-retina-data" data-retina="https://blog.topdev.vn/{{asset('theme/client/uploads/2017/01/logotopdev.png')}}" src="{{asset('theme/client/uploads/2017/01/logotopdev.png')}}" alt="" />
                                </a>
                                <a class="td-header-logo td-sticky-disable" href="index.html">
                                    <img class="td-retina-data" data-retina="https://blog.topdev.vn/{{asset('theme/client/uploads/2017/01/logotopdev.png')}}" src="{{asset('theme/client/uploads/2017/01/logotopdev.png')}}" alt="" />
                                </a>
                            </div>
                            <div class="menu-main-menu-container">
                                <ul id="menu-main-menu-1" class="sf-menu">
                                    <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-first td-menu-item td-normal-menu menu-item-1085"><a href="category/jobs/index.html">Hot Jobs</a></li>
                                    <li class="menu-item menu-item-type-taxonomy menu-item-object-category td-menu-item td-normal-menu menu-item-4"><a href="category/ask-me-anything/index.html">AMA</a></li>
                                    <li class="menu-item menu-item-type-taxonomy menu-item-object-category td-menu-item td-normal-menu menu-item-5"><a href="category/event/index.html">Event</a></li>
                                    <li class="menu-item menu-item-type-taxonomy menu-item-object-category td-menu-item td-normal-menu menu-item-7"><a href="category/hr/index.html">HR</a></li>
                                    <li class="menu-item menu-item-type-taxonomy menu-item-object-category td-menu-item td-normal-menu menu-item-8"><a href="category/lap-trinh/index.html">Lập Trình</a></li>
                                    <li class="menu-item menu-item-type-taxonomy menu-item-object-category td-menu-item td-normal-menu menu-item-9"><a href="category/phong-van/index.html">Phỏng vấn</a></li>
                                    <li class="menu-item menu-item-type-taxonomy menu-item-object-category td-menu-item td-normal-menu menu-item-1083"><a href="category/cong-nghe/index.html">Công nghệ</a></li>
                                    <li class="menu-item menu-item-type-taxonomy menu-item-object-category td-menu-item td-normal-menu menu-item-1084"><a href="category/design/index.html">Design</a></li>
                                </ul>
                            </div>
                        </div>

                        <div class="td-search-wrapper">
                            <div id="td-top-search">
                                <!-- Search -->
                                <div class="header-search-wrap">
                                    <div class="dropdown header-search">
                                        <a id="td-header-search-button" href="#" role="button" class="dropdown-toggle " data-toggle="dropdown"><i class="td-icon-search"></i></a>
                                        <a id="td-header-search-button-mob" href="#" role="button" class="dropdown-toggle " data-toggle="dropdown"><i class="td-icon-search"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="header-search-wrap">
                            <div class="dropdown header-search">
                                <div class="td-drop-down-search" aria-labelledby="td-header-search-button">
                                    <form method="get" class="td-search-form" action="https://topdev.vn/blog/">
                                        <div role="search" class="td-head-form-search-wrap">
                                            <input id="td-header-search" type="text" value="" name="s" autocomplete="off" />
                                            <input class="wpb_button wpb_btn-inverse btn" type="submit" id="td-header-search-top" value="Search" />
                                        </div>
                                    </form>
                                    <div id="td-aj-search"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>

        <!-- Instagram -->

        
    </div>
    <!--close td-outer-wrap-->

    <!--

        Theme: Newspaper by tagDiv 2016
        Version: 7.6 (rara)
        Deploy mode: deploy
        Speed booster: v4.5

        uid: 5a96c4188231b
    -->

    <script type='text/javascript' src="{{asset('theme/client/themes/Newspaper/js/tagdiv_theme.mine87d.js?ver=7.6')}}"></script>
    <script type='text/javascript' src="{{asset('theme/client/js/comment-reply.mina288.js?ver=4.8.1')}}"></script>
    <script type='text/javascript' src="{{asset('theme/client/js/wp-embed.mina288.js?ver=4.8.1')}}"></script>
    <script type='text/javascript' src="{{asset('theme/client/plugins/js_composer/assets/js/dist/js_composer_front.min972f.js?ver=5.0.1')}}"></script>

    <!-- JS generated by theme -->

    <script>
        (function() {
            var html_jquery_obj = jQuery('html');

            if (html_jquery_obj.length && (html_jquery_obj.is('.ie8') || html_jquery_obj.is('.ie9'))) {

                var path = "{{asset('theme/client/themes/Newspaper/style.css')}}";

                jQuery.get(path, function(data) {

                    var str_split_separator = '#td_css_split_separator';
                    var arr_splits = data.split(str_split_separator);
                    var arr_length = arr_splits.length;

                    if (arr_length > 1) {

                        var dir_path = "{{asset('theme/client/themes/Newspaper/index.html')}}";
                        var splited_css = '';

                        for (var i = 0; i < arr_length; i++) {
                            if (i > 0) {
                                arr_splits[i] = str_split_separator + ' ' + arr_splits[i];
                            }
                            //jQuery('head').append('<style>' + arr_splits[i] + '</style>');

                            var formated_str = arr_splits[i].replace(/\surl\(\'(?!data\:)/gi, function regex_function(str) {
                                return ' url(\'' + dir_path + '/' + str.replace(/url\(\'/gi, '').replace(/^\s+|\s+$/gm, '');
                            });

                            splited_css += "<style>" + formated_str + "</style>";
                        }

                        var td_theme_css = jQuery('link#td-theme-css');

                        if (td_theme_css.length) {
                            td_theme_css.after(splited_css);
                        }
                    }
                });
            }
        })();
    </script>

    <!-- Header style compiled by theme -->

    <style>
        .td-header-wrap .black-menu .sf-menu > .current-menu-item > a,
        .td-header-wrap .black-menu .sf-menu > .current-menu-ancestor > a,
        .td-header-wrap .black-menu .sf-menu > .current-category-ancestor > a,
        .td-header-wrap .black-menu .sf-menu > li > a:hover,
        .td-header-wrap .black-menu .sf-menu > .sfHover > a,
        .td-header-style-12 .td-header-menu-wrap-full,
        .sf-menu > .current-menu-item > a:after,
        .sf-menu > .current-menu-ancestor > a:after,
        .sf-menu > .current-category-ancestor > a:after,
        .sf-menu > li:hover > a:after,
        .sf-menu > .sfHover > a:after,
        .sf-menu ul .td-menu-item > a:hover,
        .sf-menu ul .sfHover > a,
        .sf-menu ul .current-menu-ancestor > a,
        .sf-menu ul .current-category-ancestor > a,
        .sf-menu ul .current-menu-item > a,
        .td-header-style-12 .td-affix,
        .header-search-wrap .td-drop-down-search:after,
        .header-search-wrap .td-drop-down-search .btn:hover,
        input[type=submit]:hover,
        .td-read-more a,
        .td-post-category:hover,
        .td-grid-style-1.td-hover-1 .td-big-grid-post:hover .td-post-category,
        .td-grid-style-5.td-hover-1 .td-big-grid-post:hover .td-post-category,
        .td_top_authors .td-active .td-author-post-count,
        .td_top_authors .td-active .td-author-comments-count,
        .td_top_authors .td_mod_wrap:hover .td-author-post-count,
        .td_top_authors .td_mod_wrap:hover .td-author-comments-count,
        .td-404-sub-sub-title a:hover,
        .td-search-form-widget .wpb_button:hover,
        .td-rating-bar-wrap div,
        .td_category_template_3 .td-current-sub-category,
        .dropcap,
        .td_wrapper_video_playlist .td_video_controls_playlist_wrapper,
        .wpb_default,
        .wpb_default:hover,
        .td-left-smart-list:hover,
        .td-right-smart-list:hover,
        .woocommerce-checkout .woocommerce input.button:hover,
        .woocommerce-page .woocommerce a.button:hover,
        .woocommerce-account div.woocommerce .button:hover,
        #bbpress-forums button:hover,
        .bbp_widget_login .button:hover,
        .td-footer-wrapper .td-post-category,
        .td-footer-wrapper .widget_product_search input[type="submit"]:hover,
        .woocommerce .product a.button:hover,
        .woocommerce .product #respond input#submit:hover,
        .woocommerce .checkout input#place_order:hover,
        .woocommerce .woocommerce.widget .button:hover,
        .single-product .product .summary .cart .button:hover,
        .woocommerce-cart .woocommerce table.cart .button:hover,
        .woocommerce-cart .woocommerce .shipping-calculator-form .button:hover,
        .td-next-prev-wrap a:hover,
        .td-load-more-wrap a:hover,
        .td-post-small-box a:hover,
        .page-nav .current,
        .page-nav:first-child > div,
        .td_category_template_8 .td-category-header .td-category a.td-current-sub-category,
        .td_category_template_4 .td-category-siblings .td-category a:hover,
        #bbpress-forums .bbp-pagination .current,
        #bbpress-forums #bbp-single-user-details #bbp-user-navigation li.current a,
        .td-theme-slider:hover .slide-meta-cat a,
        a.vc_btn-black:hover,
        .td-trending-now-wrapper:hover .td-trending-now-title,
        .td-scroll-up,
        .td-smart-list-button:hover,
        .td-weather-information:before,
        .td-weather-week:before,
        .td_block_exchange .td-exchange-header:before,
        .td_block_big_grid_9.td-grid-style-1 .td-post-category,
        .td_block_big_grid_9.td-grid-style-5 .td-post-category,
        .td-grid-style-6.td-hover-1 .td-module-thumb:after {
            background-color: #d7422f;
        }
        
        .woocommerce .woocommerce-message .button:hover,
        .woocommerce .woocommerce-error .button:hover,
        .woocommerce .woocommerce-info .button:hover {
            background-color: #d7422f !important;
        }
        
        .woocommerce .product .onsale,
        .woocommerce.widget .ui-slider .ui-slider-handle {
            background: none #d7422f;
        }
        
        .woocommerce.widget.widget_layered_nav_filters ul li a {
            background: none repeat scroll 0 0 #d7422f !important;
        }
        
        a,
        cite a:hover,
        .td_mega_menu_sub_cats .cur-sub-cat,
        .td-mega-span h3 a:hover,
        .td_mod_mega_menu:hover .entry-title a,
        .header-search-wrap .result-msg a:hover,
        .top-header-menu li a:hover,
        .top-header-menu .current-menu-item > a,
        .top-header-menu .current-menu-ancestor > a,
        .top-header-menu .current-category-ancestor > a,
        .td-social-icon-wrap > a:hover,
        .td-header-sp-top-widget .td-social-icon-wrap a:hover,
        .td-page-content blockquote p,
        .td-post-content blockquote p,
        .mce-content-body blockquote p,
        .comment-content blockquote p,
        .wpb_text_column blockquote p,
        .td_block_text_with_title blockquote p,
        .td_module_wrap:hover .entry-title a,
        .td-subcat-filter .td-subcat-list a:hover,
        .td-subcat-filter .td-subcat-dropdown a:hover,
        .td_quote_on_blocks,
        .dropcap2,
        .dropcap3,
        .td_top_authors .td-active .td-authors-name a,
        .td_top_authors .td_mod_wrap:hover .td-authors-name a,
        .td-post-next-prev-content a:hover,
        .author-box-wrap .td-author-social a:hover,
        .td-author-name a:hover,
        .td-author-url a:hover,
        .td_mod_related_posts:hover h3 > a,
        .td-post-template-11 .td-related-title .td-related-left:hover,
        .td-post-template-11 .td-related-title .td-related-right:hover,
        .td-post-template-11 .td-related-title .td-cur-simple-item,
        .td-post-template-11 .td_block_related_posts .td-next-prev-wrap a:hover,
        .comment-reply-link:hover,
        .logged-in-as a:hover,
        #cancel-comment-reply-link:hover,
        .td-search-query,
        .td-category-header .td-pulldown-category-filter-link:hover,
        .td-category-siblings .td-subcat-dropdown a:hover,
        .td-category-siblings .td-subcat-dropdown a.td-current-sub-category,
        .widget a:hover,
        .widget_calendar tfoot a:hover,
        .woocommerce a.added_to_cart:hover,
        #bbpress-forums li.bbp-header .bbp-reply-content span a:hover,
        #bbpress-forums .bbp-forum-freshness a:hover,
        #bbpress-forums .bbp-topic-freshness a:hover,
        #bbpress-forums .bbp-forums-list li a:hover,
        #bbpress-forums .bbp-forum-title:hover,
        #bbpress-forums .bbp-topic-permalink:hover,
        #bbpress-forums .bbp-topic-started-by a:hover,
        #bbpress-forums .bbp-topic-started-in a:hover,
        #bbpress-forums .bbp-body .super-sticky li.bbp-topic-title .bbp-topic-permalink,
        #bbpress-forums .bbp-body .sticky li.bbp-topic-title .bbp-topic-permalink,
        .widget_display_replies .bbp-author-name,
        .widget_display_topics .bbp-author-name,
        .footer-text-wrap .footer-email-wrap a,
        .td-subfooter-menu li a:hover,
        .footer-social-wrap a:hover,
        a.vc_btn-black:hover,
        .td-smart-list-dropdown-wrap .td-smart-list-button:hover,
        .td_module_17 .td-read-more a:hover,
        .td_module_18 .td-read-more a:hover,
        .td_module_19 .td-post-author-name a:hover,
        .td-instagram-user a {
            color: #d7422f;
        }
        
        a.vc_btn-black.vc_btn_square_outlined:hover,
        a.vc_btn-black.vc_btn_outlined:hover,
        .td-mega-menu-page .wpb_content_element ul li a:hover {
            color: #d7422f !important;
        }
        
        .td-next-prev-wrap a:hover,
        .td-load-more-wrap a:hover,
        .td-post-small-box a:hover,
        .page-nav .current,
        .page-nav:first-child > div,
        .td_category_template_8 .td-category-header .td-category a.td-current-sub-category,
        .td_category_template_4 .td-category-siblings .td-category a:hover,
        #bbpress-forums .bbp-pagination .current,
        .post .td_quote_box,
        .page .td_quote_box,
        a.vc_btn-black:hover {
            border-color: #d7422f;
        }
        
        .td_wrapper_video_playlist .td_video_currently_playing:after {
            border-color: #d7422f !important;
        }
        
        .header-search-wrap .td-drop-down-search:before {
            border-color: transparent transparent #d7422f transparent;
        }
        
        .block-title > span,
        .block-title > a,
        .block-title > label,
        .widgettitle,
        .widgettitle:after,
        .td-trending-now-title,
        .td-trending-now-wrapper:hover .td-trending-now-title,
        .wpb_tabs li.ui-tabs-active a,
        .wpb_tabs li:hover a,
        .vc_tta-container .vc_tta-color-grey.vc_tta-tabs-position-top.vc_tta-style-classic .vc_tta-tabs-container .vc_tta-tab.vc_active > a,
        .vc_tta-container .vc_tta-color-grey.vc_tta-tabs-position-top.vc_tta-style-classic .vc_tta-tabs-container .vc_tta-tab:hover > a,
        .td-related-title .td-cur-simple-item,
        .woocommerce .product .products h2,
        .td-subcat-filter .td-subcat-dropdown:hover .td-subcat-more {
            background-color: #d7422f;
        }
        
        .woocommerce div.product .woocommerce-tabs ul.tabs li.active {
            background-color: #d7422f !important;
        }
        
        .block-title,
        .td-related-title,
        .wpb_tabs .wpb_tabs_nav,
        .vc_tta-container .vc_tta-color-grey.vc_tta-tabs-position-top.vc_tta-style-classic .vc_tta-tabs-container,
        .woocommerce div.product .woocommerce-tabs ul.tabs:before {
            border-color: #d7422f;
        }
        
        .td_block_wrap .td-subcat-item .td-cur-simple-item {
            color: #d7422f;
        }
        
        .td-grid-style-4 .entry-title {
            background-color: rgba(215, 66, 47, 0.7);
        }
    </style>

    <!-- Facebook Pixel Code -->
    <script>
        ! function(f, b, e, v, n, t, s) {
            if (f.fbq) return;
            n = f.fbq = function() {
                n.callMethod ?
                    n.callMethod.apply(n, arguments) : n.queue.push(arguments)
            };
            if (!f._fbq) f._fbq = n;
            n.push = n;
            n.loaded = !0;
            n.version = '2.0';
            n.queue = [];
            t = b.createElement(e);
            t.async = !0;
            t.src = v;
            s = b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t, s)
        }(window,
            document, 'script', '../../connect.facebook.net/en_US/fbevents.js');
        fbq('init', '103882006638557'); // Insert your pixel ID here.
        fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=103882006638557&amp;ev=PageView&amp;noscript=1" /></noscript>
    <!-- DO NOT MODIFY -->
    <!-- End Facebook Pixel Code -->
    <!-- Techtalk Follow Code -->
    <script type="text/javascript">
        (function() {
            var s1 = document.createElement("script"),
                s0 = document.getElementsByTagName("script")[0];
            s1.async = true;
            s1.src = '../../tr.topdevvn.com/js/follow.js';
            s1.charset = 'UTF-8';
            s1.setAttribute('crossorigin', '*');
            s0.parentNode.insertBefore(s1, s0);
        })();
    </script>
    <!-- End Techtalk Follow Code -->

</body>

<!-- Mirrored from topdev.vn/blog/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 28 Feb 2018 15:01:07 GMT -->

</html>
